  
  
  
  

  
  
  
  
  
  
  


  



// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Connection String:      "server=s0134dbtemp123; user=quantra; password=**zapped**;; database=NorthWindDatabase; pooling=true; Max Pool Size=100; Min Pool Size=8"
// ------------------------------------------------------------------------------------------------

// -----------------------------------------------------------------------------------------
// Failed to read database schema in LoadTables() - Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
// -----------------------------------------------------------------------------------------


// -----------------------------------------------------------------------------------------
// Failed to read database schema for stored procedures - A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
// -----------------------------------------------------------------------------------------


